master_data/urls.py
from django.urls import include, path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('master_data/country', country, name='country'),
    path('master_data/country/add', country_add, name='country_add'),
    path('master_data/city', city, name='city'),
    path('master_data/city/add', city_add, name='city_add'),
    path('master_data/measuring_unit', measuring_unit, name='measuring_unit'),
    path('master_data/measuring_unit/add', measuring_unit_add, name='measuring_unit_add'),
    path('master_data/company', company, name='company'),
    path('master_data/company/add', company_add, name='company_add'),
    path('master_data/plant', plant, name='plant'),
    path('master_data/plant/add', plant_add, name='plant_add'),
    path('ajax/load-companies/', load_company, name='ajax_load_companies'), # AJAX
]

qtrack/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master_data/', include('master_data.urls')),
    path('', include('master_data.urls')),
]

master_data/models.py
from typing import ChainMap
from django.db import models
from django.db.models.fields.related import ForeignKey


# Create your models here.


class Country(models.Model):
    country_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.country_name

    def __unicode__(self):
        return self.country_name


class MeasuringUnits(models.Model):
    measuring_unit_name = models.CharField(max_length=50, unique=True)
    measuring_unit_code = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.measuring_unit_name

    def __unicode__(self):
        return self.measuring_unit_name


class City(models.Model):
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE, null=True)
    city_name = models.CharField(max_length=50)

    def __str__(self):
        return self.city_name

    def country_name(self):
        return self.country.country_name

    def __unicode__(self):
        return self.city_name


class Company(models.Model):
    company_name = models.CharField(max_length=100, null=False)
    company_code = models.CharField(max_length=30, null=False)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.company_name

    def country_name(self):
        return self.country.country_name

    def __unicode__(self):
        return self.company_name


class Plant(models.Model):
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True)
    plant_name = models.CharField(max_length=30, null=False)
    plant_code = models.CharField(max_length=30, null=False)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.plant_name

    def country_name(self):
        return self.country.country_name

    def company_name(self):
        return self.company.company_name

    def __unicode__(self):
        return self.plant_name


class Department(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=False)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE, null=False)
    department_name = models.CharField(max_length=50, null=False)
    department_code = models.CharField(max_length=15, null=False)

    def __str__(self):
        return self.department_name

    def company_name(self):
        return self.company.company_name

    def plant_name(self):
        return self.plant.plant_name

    def __unicode__(self):
        return self.department_name

master_data/forms.py
from django import forms
from .models import *


class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ['country_name']

        widgets = {
            'country_name': forms.TextInput(attrs={'class': 'form-control'})
        }


class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ['country', 'city_name']

        widgets = {
            'country': forms.Select(attrs={'class': 'form-control'}),
            'city_name': forms.TextInput(attrs={'class': 'form-control'})
        }


class MeasuringUnitForm(forms.ModelForm):
    class Meta:
        model = MeasuringUnits
        fields = ['measuring_unit_name', 'measuring_unit_code']

        widgets = {
            'measuring_unit_name': forms.TextInput(attrs={'class': 'form-control'}),
            'measuring_unit_code': forms.TextInput(attrs={'class': 'form-control'}),

        }


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['company_name', 'company_code', 'country']

        widgets = {
            'country': forms.Select(attrs={'class': 'form-control'}),
            'company_name': forms.TextInput(attrs={'class': 'form-control'}),
            'company_code': forms.TextInput(attrs={'class': 'form-control'}),
        }


class PlantForm(forms.ModelForm):
    class Meta:
        model = Plant
        fields = ('country', 'company', 'plant_name', 'plant_code')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['company'].queryset = Company.objects.none()

            if 'country' in self.data:
                try:
                    country_id = int(self.data.get('country'))
                    self.fields['company'].queryset = Company.objects.filter(country_id=country_id).order_by(
                        'company_name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty company queryset
            elif self.instance.pk:
                self.fields['company'].queryset = self.instance.country.company_set.order_by('company_name')

        widgets = {
            'country': forms.Select(attrs={'class': 'form-control'}),
            'company': forms.Select(attrs={'class': 'form-control'}),
            'plant_name': forms.TextInput(attrs={'class': 'form-control'}),
            'plant_code': forms.TextInput(attrs={'class': 'form-control'}),
        }

master_data/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Country, Company, City, MeasuringUnits, Plant
from .forms import CountryForm, CityForm, MeasuringUnitForm, CompanyForm, PlantForm


# Create your views here.
def index(request):
    return render(request, 'home.html')


def country(request):
    country = Country.objects.all()

    context = {'country': country,
               }
    return render(request, 'master_data/country/country_list.html', context)


def country_add(request):
    form = CountryForm(request.POST)
    # check whether it's valid:
    if form.is_valid():
        form.save()
        return redirect('/master_data/country')

    return render(request, 'master_data/country/country_add.html', {'form': form})


def city(request):
    city = City.objects.all()

    context = {'country': country,
               'city': city
               }
    return render(request, 'master_data/city/city_list.html', context)


def city_add(request):
    form = CityForm(request.POST)
    # check whether it's valid:
    if form.is_valid():
        form.save()
        return redirect('/master_data/city')

    return render(request, 'master_data/city/city_add.html', {'form': form})


def measuring_unit(request):
    measuring_unit = MeasuringUnits.objects.all()

    context = {'measuring_unit': measuring_unit,
               }
    return render(request, 'master_data/measuring_unit/measuring_unit_list.html', context)


def measuring_unit_add(request):
    form = MeasuringUnitForm(request.POST)
    # check whether it's valid:
    if form.is_valid():
        form.save()
        return redirect('/master_data/measuring_unit')

    return render(request, 'master_data/measuring_unit/measuring_unit_add.html', {'form': form})


def company(request):
    company = Company.objects.all()

    context = {'country': country,
               'company': company
               }
    return render(request, 'master_data/company/company_list.html', context)


def company_add(request):
    form = CompanyForm(request.POST)
    # check whether it's valid:
    if form.is_valid():
        form.save()
        return redirect('/master_data/company')

    return render(request, 'master_data/company/company_add.html', {'form': form})


def plant(request):
    plant = Plant.objects.all()

    context = {'country': country,
               'company': company,
               'plant': plant
               }
    return render(request, 'master_data/plant/plant_list.html', context)


def plant_add(request):
    form = PlantForm(request.POST)
    # check whether it's valid:
    if form.is_valid():
        form.save()
        return redirect('/master_data/plant')

    return render(request, 'master_data/plant/plant_add.html', {'form': form})


# AJAX
def load_company(request):
    country_id = request.GET.get('country')
    companies = Company.objects.filter(country_id=country_id).order_by('company_name')
    return render(request, 'master_data/company_dropdown_list_options.html', {'companies': companies})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

master_data/templates/master_data/plant/plant_add.html
{% extends 'index.html' %}
        {% load static %}

        {% block title %}
          Add Plant
        {% endblock %}
        {% block description %}
         {{ setting.description }}
        {% endblock %}
        {% block keywords %}
            {{ setting.keywords }}
        {% endblock %}

  <!-- Navbar -->
{% block navbar %}
 {% include 'navbar.html' %}
        {% endblock %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
   {% block sidebar %}
 {% include 'sidebar.html' %}
        {% endblock %}

  <!-- Content Wrapper. Contains page content -->

    <!-- Content Header (Page header) -->
   {% block content_header_title %}
            Add Plant
         {% endblock %}
         {% block content_header_breadcrumb %}
             Add Plant
         {% endblock %}
    <div class="content-wrapper">

     {% block content %}
    <!-- Main content -->
 <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">

      <div class="card card-primary">
            <form method="post" id="pForm" data-companies-url="{% url 'ajax_load_companies' %}">
              <div class="card-header">
                <h3 class="card-title">Add Plant</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->

                <div class="card-body">
                  <div class="form-group">
                    {% csrf_token %}
                      {{ form.as_p }}
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
      </div>

          </div>
        </div>
      </div>
 </section>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

<!-- ./wrapper -->

{% endblock %}
    </div>

 <!-- /.content-wrapper -->
  {% block footer %}
            {% include 'footer.html' %}
  {% endblock %}
 <script>
    $("#id_country").change(function () {
      var url = $("#pForm").attr("data-companies-url");  // get the url of the `load_cities` view
      var countryId = $(this).val();  // get the selected country ID from the HTML input
        console.log(countryId);
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'country': countryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_company").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

master_data/templates/master_data/plant/plant_list.html
{% extends 'index.html' %}
        {% load static %}

        {% block title %}
          Plant List
        {% endblock %}
        {% block description %}
            {{ setting.description }}
        {% endblock %}
        {% block keywords %}
            {{ setting.keywords }}
        {% endblock %}
      <!-- Navbar -->
    {% block navbar %}
     {% include 'navbar.html' %}
    {% endblock %}
      <!-- /.navbar -->

      <!-- Main Sidebar Container -->
    {% block sidebar %}
     {% include 'sidebar.html' %}
    {% endblock %}

  <!-- Content Wrapper. Contains page content -->
 
    <!-- Content Header (Page header) -->
         {% block content_header_title %}
            Plant List
         {% endblock %}
         {% block content_header_breadcrumb %}
             Plant List
         {% endblock %}
 <div class="content-wrapper">
  {% block content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
           
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Plant</h3>
                 <div class="card-tools center"><a href="{% url 'plant_add' %}" class="btn btn-primary btn-sm" >Add</a></div>
                
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Company</th>
                    <th>Plant Name</th>
                    <th>Plant Code</th>
                    <th>Country</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for c in plant %}
                  <tr>
                    <td>{{c.company}}</td>
                    <td>{{c.plant_name}}</td>
                    <td>{{c.plant_code}}</td>
                    <td>{{c.country}}</td>

                  </tr>
                  {% endfor%}
                
                  
                  </tbody>
                  
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
      

 
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

<!-- ./wrapper -->

{% endblock %}



 <!-- /.content-wrapper -->
  {% block footer %}
            {% include 'footer.html' %}
  {% endblock %}